// src/api/orderApi.ts
import { orderApi } from './apiClient';
import type { OrderResponse } from '../types/product'; 

/**
 * ✅ Create a new order from current cart
 * Design IDs (SKUs) are snapshotted into order_items during this process.
 */
export const createOrder = async (): Promise<OrderResponse> => {
  const response = await orderApi.post('');
  return response.data;
};

/**
 * ✅ Fetch specific order details
 * Includes the designIdentifier for each item in the order.
 */
export const getOrderDetails = async (orderId: number): Promise<OrderResponse> => {
  const response = await orderApi.get(`/${orderId}`);
  return response.data;
};

/**
 * ✅ Fetch user's order history
 * Used by the Orders page to display the "Design Passport" / SKU boxes.
 */
export const getMyOrders = async (): Promise<OrderResponse[]> => {
  const response = await orderApi.get('');
  return response.data;
};

/**
 * ✅ Get secure asset download link
 * Only available for PAID orders.
 */
export const getOrderDownloadLink = async (orderId: number): Promise<{ downloadUrl: string }> => {
  const response = await orderApi.get(`/${orderId}/download`);
  return response.data;
};

/**
 * ✅ NEW: Functional Invoice Download
 * Retrieves the PDF blob generated by the Order Service.
 */
export const downloadInvoicePdf = async (orderId: number) => {
  try {
    console.log(`📡 Requesting PDF Invoice for Order #${orderId}...`);
    
    const response = await orderApi.get(`/${orderId}/invoice`, {
      responseType: 'blob', // ⚡ CRITICAL: Tells Axios to handle binary data
    });
    
    // Create a Blob from the PDF stream
    const file = new Blob([response.data], { type: 'application/pdf' });
    
    // Create a temporary URL for the browser to "see" the file
    const fileURL = window.URL.createObjectURL(file);
    
    // Create a hidden anchor element to trigger the system "Save As" dialog
    const fileLink = document.createElement('a');
    fileLink.href = fileURL;
    fileLink.setAttribute('download', `Invoice-RDC-${orderId}.pdf`);
    
    document.body.appendChild(fileLink);
    fileLink.click();
    
    // Cleanup: Remove the element and the temporary URL to free memory
    fileLink.remove();
    window.URL.revokeObjectURL(fileURL);
    
    console.log(`✅ Invoice-RDC-${orderId}.pdf downloaded successfully.`);
  } catch (error) {
    console.error('❌ Download failed:', error);
    alert('Could not download invoice. The server may be busy generating your PDF.');
  }
};

export default orderApi;